### ISSUE TITLE
Measurement Run Reset -> Start leads to exception

### ISSUE THREAD

**Issue by JanKue** [osl2/PhyPiDAQ#22]
Symptom: Resetting a measurement run and then starting it again (in the GUI) leads to a NullPointerException.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at edu.kit.freejdaq.cache.MRunTiming.extractChannelIdsOutOfMRunInfo(MRunTiming.java:110)
	at edu.kit.freejdaq.cache.MRunTiming.<init>(MRunTiming.java:48)
	at edu.kit.freejdaq.backend.MRunAgent.start(MRunAgent.java:45)
	at edu.kit.freejdaq.model.core.MeasurementRun.start(MeasurementRun.java:205)
	at edu.kit.freejdaq.controller.commands.StartRunCommand.execute(StartRunCommand.java:33)
	at edu.kit.freejdaq.controller.commands.CommandManager.runCommand(CommandManager.java:55)
	at edu.kit.freejdaq.controller.igui.ButtonAction.runConfigurationPressed(ButtonAction.java:68)
	at edu.kit.freejdaq.gui.menues.ButtonField.actionPerformed(ButtonField.java:77)
```

**Comment by JanKue** [comment]
Note: Model and Backend both in theory support starting a new measurement run after the previous measurement run was reset.

**Comment by JanKue** [comment]
Cause: The same `MRunInfo` instance cannot be used to start a second measurement run.

Possible solution: Create a new instance of MRunInfo when resetting the measurement run.
